# -*- coding: utf-8 -*-
"""DA_Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMLJQ_CsOOo8yLGMtEq27R8yO9tbe_Jh
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/train.csv')

df.tail()

df.head(4)

df.shape

df.dtypes

df.info()

df.describe()

df.isnull().sum()

df['Postal Code'].fillna('Unknown', inplace=True)

df.isnull().sum()

sns.heatmap(df.isnull(),cbar=False)

df.duplicated().sum()

df['Region'] = df['Region'].str.strip().str.title()
df['Category'] = df['Category'].str.strip().str.title()

df['Order Date'] = pd.to_datetime(df['Order Date'],dayfirst=True)

df['Month_Year'] = df['Order Date'].dt.to_period('M').astype(str)

df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

plt.figure(figsize=(8,4))

sns.boxplot(x=df['Sales'])
plt.title('Outliers of Sales')
plt.show()

df=df[df['Sales']>0]

df.describe()

df.info()

df.head(6)

df['Postal Cod']= df['Postal Code'].astype(str)

df.tail(2)

df.to_csv('Cleaned_sales.csv',index=False)

files.download('Cleaned_sales.csv')